### ISSUE TITLE
Requesting attachment of documents

### ISSUE THREAD

**Issue by Nagaraj-Boopathi** [Nagaraj-Boop/WhatsUp-Development#4]
Dear Nagaraj-Boop,

It would be great if this app is capable of attaching the documents as well.
kindly add this feature.

**Comment by Nagaraj-Boop** [comment]
Dear Nagaraj-Boopathi,

Thanks for suggesting this feature, we will add and let you know.

**Comment by Nagaraj-Boop** [comment]
Dear Nagaraj-Boopathi
This feature is going to make our product great
Thanks
